---
# tasks file for roles/influxdb
- name: Install gpg
  ansible.builtin.apt:
    name:
      - gnupg
      - software-properties-common
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Influxdb key
  ansible.builtin.get_url:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    dest: /etc/apt/keyrings/influxdata.asc
    mode: '0644'
    checksum: sha256:393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c

- name: Add repository
  ansible.builtin.apt_repository:
    filename: influxdata
    repo: "deb [signed-by=/etc/apt/keyrings/influxdata.asc] https://repos.influxdata.com/debian stable main"
    state: present

- name: Install Influxdb
  ansible.builtin.apt:
    name:
      - influxdb2
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Start service influxdb
  ansible.builtin.systemd:
    name: influxdb
    state: started
    enabled: true
