---
- name: Install Influxd and Grafana
  hosts: influx
  become: true
  roles:
    - influxdb
    - grafana
    - icinga2_client
- name: Install Telegraf
  hosts: servers
  become: true
  roles:
    - telegraf
