---
- name: Install Influxd and Grafana
  hosts: influx
  become: true
  roles:
    - {role: 'influxdb', tags: 'influxdb'}
    - {role: 'grafana', tags: 'grafana'}
    - {role: 'icinga2_client', tags: 'icinga2_client'}
- name: Install Telegraf
  hosts: servers
  become: true
  roles:
    - {role: 'telegraf', tags: 'telegraf'}
